<a href="https://colab.research.google.com/github/Ayush17112002/Ayush17112002/blob/main/data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [76]:
import numpy as np #numpy is used to handle arrays
import matplotlib.pyplot as plt #matplotlib.pyplot is used for graphs
import pandas as pd #pandas is used to graph

## Importing the dataset

In [77]:
dataset = pd.read_csv("Data.csv") #it will read the tabular format data from data.csv file and return dataframe as output
print(dataset)
x = dataset.iloc[:,:-1].values #x is the matrix of independent variables(aka features)
y = dataset.iloc[:,-1].values #y is the dependent variable vector that we want to predict for each row of data

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


## Taking care of missing data

In [78]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="mean"); #configuring the imputer to set missing values by the mean of that column values
imputer.fit(x[:,1:3]) #calculating the mean of each column specified in arg over all rows
x[:,1:3] = imputer.transform(x[:,1:3])

In [79]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [80]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [81]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [82]:
#this is the phase where you will split your dataset into test and training set 
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=1)


In [83]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [84]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [85]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [86]:
print(y_test)

[0 1]


## Feature Scaling

In [87]:
#to avoid our ML model from misinterpreting the larger values of a column to dominate over the smaller values of another column, we scale our data so that all features(independent variable) contribute equally
from sklearn.preprocessing import StandardScaler
sc = StandardScaler() #standardization tool
x_train[:,3:-1] = sc.fit_transform(x_train[:,3:-1]);
x_test[:,3:-1] = sc.transform(x_test[:,3:-1]);
print(x_train, x_test)

[[0.0 0.0 1.0 -0.19159184384578545 52000.0]
 [0.0 1.0 0.0 -0.014117293757057777 63777.77777777778]
 [1.0 0.0 0.0 0.566708506533324 72000.0]
 [0.0 0.0 1.0 -0.30453019390224867 61000.0]
 [0.0 0.0 1.0 -1.9018011447007988 48000.0]
 [1.0 0.0 0.0 1.1475343068237058 79000.0]
 [0.0 1.0 0.0 1.4379472069688968 83000.0]
 [1.0 0.0 0.0 -0.7401495441200351 58000.0]] [[0.0 1.0 0.0 -1.4661817944830124 54000.0]
 [1.0 0.0 0.0 -0.44973664397484414 67000.0]]
